-- Добавление всех персонажей Dota 2 (без биографий - пользователь добавит сам)

INSERT INTO heroes (name, title, attribute, bio_image_url) VALUES
('Abaddon', 'Lord of Avernus', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abaddon.png'),
('Alchemist', 'Razzil Darkbrew', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/alchemist.png'),
('Ancient Apparition', 'Kaldr', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ancient_apparition.png'),
('Anti-Mage', 'Magina', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/antimage.png'),
('Arc Warden', 'Zet', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/arc_warden.png'),
('Axe', 'Mogul Khan', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/axe.png'),
('Bane', 'Atropos', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bane.png'),
('Batrider', 'Jin''zakk', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/batrider.png'),
('Beastmaster', 'Karroch', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/beastmaster.png'),
('Bloodseeker', 'Strygwyr', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bloodseeker.png'),
('Bounty Hunter', 'Gondar', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bounty_hunter.png'),
('Brewmaster', 'Mangix', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/brewmaster.png'),
('Bristleback', 'Rigwarl', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bristleback.png'),
('Broodmother', 'Black Arachnia', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/broodmother.png'),
('Centaur Warrunner', 'Bradwarden', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/centaur.png'),
('Chaos Knight', 'Nessaj', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chaos_knight.png'),
('Chen', 'Chen', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chen.png'),
('Clinkz', 'Clinkz', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/clinkz.png'),
('Clockwerk', 'Rattletrap', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rattletrap.png'),
('Crystal Maiden', 'Rylai', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/crystal_maiden.png'),
('Dark Seer', 'Ish''kafel', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_seer.png'),
('Dark Willow', 'Mireska', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_willow.png'),
('Dawnbreaker', 'Valora', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png'),
('Dazzle', 'Dazzle', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dazzle.png'),
('Death Prophet', 'Krobelus', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/death_prophet.png'),
('Disruptor', 'Thrall', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/disruptor.png'),
('Doom', 'Lucifer', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/doom_bringer.png'),
('Dragon Knight', 'Knight Davion', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dragon_knight.png'),
('Drow Ranger', 'Traxex', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/drow_ranger.png'),
('Earth Spirit', 'Kaolin', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earth_spirit.png'),
('Earthshaker', 'Raigor Stonehoof', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earthshaker.png'),
('Elder Titan', 'Elder Titan', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/elder_titan.png'),
('Ember Spirit', 'Xin', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ember_spirit.png'),
('Enchantress', 'Aiushtha', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enchantress.png'),
('Enigma', 'Darchrow', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enigma.png'),
('Faceless Void', 'Darkterror', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/faceless_void.png'),
('Grimstroke', 'Grimstroke', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/grimstroke.png'),
('Gyrocopter', 'Aurel', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/gyrocopter.png'),
('Hoodwink', 'Hoodwink', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/hoodwink.png'),
('Huskar', 'Huskar', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/huskar.png'),
('Invoker', 'Carl', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/invoker.png'),
('Io', 'Io', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/wisp.png'),
('Jakiro', 'Jakiro', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/jakiro.png'),
('Juggernaut', 'Yurnero', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/juggernaut.png'),
('Keeper of the Light', 'Ezalor', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png'),
('Kunkka', 'Kunkka', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kunkka.png'),
('Legion Commander', 'Tresdin', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/legion_commander.png'),
('Leshrac', 'Leshrac', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/leshrac.png'),
('Lich', 'Ethreain', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lich.png'),
('Lifestealer', 'N''aix', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/life_stealer.png'),
('Lina', 'Lina', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lina.png'),
('Lion', 'Lion', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lion.png'),
('Lone Druid', 'Syllabear', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lone_druid.png'),
('Luna', 'Luna', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/luna.png'),
('Lycan', 'Banehallow', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lycan.png'),
('Magnus', 'Magnus', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/magnataur.png'),
('Marci', 'Marci', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/marci.png'),
('Mars', 'Mars', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mars.png'),
('Medusa', 'Medusa', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/medusa.png'),
('Meepo', 'Meepo', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/meepo.png'),
('Mirana', 'Mirana', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mirana.png'),
('Monkey King', 'Sun Wukong', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/monkey_king.png'),
('Morphling', 'Morphling', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/morphling.png'),
('Muerta', 'Muerta', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/muerta.png'),
('Naga Siren', 'Slithice', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/naga_siren.png'),
('Nature''s Prophet', 'Furion', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/furion.png'),
('Necrophos', 'Rotund''jere', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/necrolyte.png'),
('Night Stalker', 'Balanar', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/night_stalker.png'),
('Nyx Assassin', 'Nyx', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nyx_assassin.png'),
('Ogre Magi', 'Aggron Stonebreak', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ogre_magi.png'),
('Omniknight', 'Purist Thunderwrath', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/omniknight.png'),
('Oracle', 'Nerif', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/oracle.png'),
('Outworld Destroyer', 'Harbinger', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png'),
('Pangolier', 'Donte Panlin', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pangolier.png'),
('Phantom Assassin', 'Mortred', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_assassin.png'),
('Phantom Lancer', 'Azwraith', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_lancer.png'),
('Phoenix', 'Icarus', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phoenix.png'),
('Primal Beast', 'Primal Beast', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/primal_beast.png'),
('Puck', 'Puck', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/puck.png'),
('Pudge', 'Pudge', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pudge.png'),
('Pugna', 'Pugna', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pugna.png'),
('Queen of Pain', 'Akasha', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/queenofpain.png'),
('Razor', 'Razor', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/razor.png'),
('Riki', 'Riki', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/riki.png'),
('Rubick', 'Rubick', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rubick.png'),
('Sand King', 'Crixalis', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sand_king.png'),
('Shadow Demon', 'Eredar', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_demon.png'),
('Shadow Fiend', 'Nevermore', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nevermore.png'),
('Shadow Shaman', 'Rhasta', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_shaman.png'),
('Silencer', 'Nortrom', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/silencer.png'),
('Skywrath Mage', 'Dragonus', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skywrath_mage.png'),
('Slardar', 'Slardar', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slardar.png'),
('Slark', 'Slark', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slark.png'),
('Snapfire', 'Beatrix', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/snapfire.png'),
('Sniper', 'Kardel Sharpeye', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sniper.png'),
('Spectre', 'Mercurial', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spectre.png'),
('Spirit Breaker', 'Barathrum', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spirit_breaker.png'),
('Storm Spirit', 'Raijin Thunderkeg', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/storm_spirit.png'),
('Sven', 'Sven', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sven.png'),
('Techies', 'Squee, Spleen and Spoon', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/techies.png'),
('Templar Assassin', 'Lanaya', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/templar_assassin.png'),
('Terrorblade', 'Terrorblade', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/terrorblade.png'),
('Tidehunter', 'Leviathan', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tidehunter.png'),
('Timbersaw', 'Rizzrack', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shredder.png'),
('Tinker', 'Boush', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tinker.png'),
('Tiny', 'Tiny', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tiny.png'),
('Treant Protector', 'Rooftrellen', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/treant.png'),
('Troll Warlord', 'Jah''rakal', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/troll_warlord.png'),
('Tusk', 'Ymir', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tusk.png'),
('Underlord', 'Vrogros', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abyssal_underlord.png'),
('Undying', 'Dirge', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/undying.png'),
('Ursa', 'Ulfsaar', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ursa.png'),
('Vengeful Spirit', 'Shendelzare', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/vengefulspirit.png'),
('Venomancer', 'Lesale', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/venomancer.png'),
('Viper', 'Netherdrake', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/viper.png'),
('Visage', 'Visage', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/visage.png'),
('Void Spirit', 'Inai', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/void_spirit.png'),
('Warlock', 'Demnok Lannik', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/warlock.png'),
('Weaver', 'Skitskurr', 'AGI', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/weaver.png'),
('Windranger', 'Lyralei', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/windrunner.png'),
('Winter Wyvern', 'Auroth', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/winter_wyvern.png'),
('Witch Doctor', 'Zharvakko', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/witch_doctor.png'),
('Wraith King', 'Ostarion', 'STR', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skeleton_king.png'),
('Zeus', 'Zeus', 'INT', 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/zuus.png')
ON CONFLICT DO NOTHING;

